spring:
  datasource:
    url:  jdbc:mysql://chaeeundatabase.cepatczvmw8n.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    #jdbc:mysql://localhost:3306/test
    username: chaeeun
    password: 19980525
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true  # (3) SQL pretty print